openapi: 3.0.0
info:
  title: Mafia.gg api
  description: none needed
  version 0.1.9

servers:
  - url: https://mafia.gg/api

components:
  schemas:
    SelfUser:
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
        timeFormat:
          type: string
        hostBannedUsernames:
          type: array
          items:
            type: string
        isPatreonLinked:
          type: boolean
        activePatreon:
          type: boolean
        needsVerification:
          type: boolean
        createdAt:
          type: string
          format: date-time        

paths:
  /user-session:
    post:
      summary: Used to log into an account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
                  format: password
      resposes:
        '200':
          description: Returns the user.
          content:
            application/json:
              $ref: '#/components/schemas/SelfUser'
        '401':
          description: Wrong username or password.
          content:
            text/plain:
              'Unauthorized'